### PR TITLE
Update rollup and changing

### PR DESCRIPTION
**Pull request by hjemmel**
I have done some minor changes:

- Update rollup version;
- Add test-watch on npm to watch files and re-run the test
- changed library to improve the coverage
- created option.js that holds the logic to get the default options

### CODE REVIEW

**Comment by hjemmel** [comment]
I also have enabled https://greenkeeper.io in my fork, in that way I can track the libraries update.

**Comment by deitch** [comment]
This is nice. Mixing a bunch of things but minor enough to merge in.

Really should use branches to keep each one separate. This would have been good with several PRs:

1. Bump rollup
2. Change rollup command-line options
3. Extract options

Leave it for now, though.

Just bump patch version so can publish?

**Comment by hjemmel** [comment]
Sorry I always have this bad behavior to not separate the commits :(

I think you can just bump and publish

**Comment by deitch** [comment]
Done. Will bump and publish.

> Sorry I always have this bad behavior to not separate the commits :(

Yeah. You are doing PRs off of your own copy on `master`. If you do your own branches and PRs off of there, it gets much easier. That is my style, anyways. Lots of very short-lived branches.

**Comment by hjemmel** [comment]
that's probably the best away todo, I usually do that at work!

**Pull request merged**
