### PR TITLE
Added support for Objects in arrays and speedup

### PR DESCRIPTION
**Pull request by janober**
hi,

was playing around with it a little bit and realized that it was not possible to search in objects that are in arrays. Had already some code programmed for another project which did that correctly so I just changed it a little bit and plugged it in.

While I was doing it I also cleaned up the indentation. It seems like that tabs and spaced where mixed and so it displayed it for me all over the place. Did separate the clean-up commits that it is easier to see what in the code I actually changed.

Added also tests for the new functions. All seems to work fine.

### CODE REVIEW

**Comment by deitch** [comment]
Lot of changes here. I am going to leave the indentation and focus on the functional commits for now.

**Comment by deitch** [comment]
Can you explain the functional changes a little more in detail? Here is what I see:

1. Search objects that are in arrays. What does this mean? Practical example? 
2. Speed up search. Does converting it to lower case and doing `field.indexOf(s) !== -1` actually work that much better? Same for just lower-case and matching `s === field` versus the regex?
3. Create the options and reference, 20% faster? What did you do here?

If these actually make it 20% faster for each, that is great, love to include it. Please explain it, though. Thanks for the PR!

**Comment by janober** [comment]
Sure.
1. You can find the practical example in the tests of the commit. I added it there. You can find it here: https://github.com/janober/searchjs/commit/34ff7f3cd18861acc4240e1980f79a5954ac98b2
2. I currently have something in my web-app which does similar things like searchjs. So I wanted to compare the speed of both. So wrote a short script for nodejs which creates an array with 1000 entries and it does a search in it 100x. The result was that searchjs was 10x slower. Which is understandable because of the many additional features it has compared to my solution. However started then to see if I can speed it up at least a little bit. So tried different things, one thing that caught my eye were the regexes which are known to be not incredible fast. So I started to experiment a little bit. The result was that after that change it was in average 20% faster. You can just write a short test yourself to confirm.
3. More or less did I simply moved out the code (from "matchObj") which initializes the options. The reason for that is that in the prev. solution it did do it again and again for every entry in the array. So if I look through an array with 10.000 entries it would run the option initialization for the base-query 10.000 times. But that is not needed because the base query does not change. I can run it just once instead. You can also confirm the speed increase there with the simple script described above.

**Comment by deitch** [comment]
**10x slower???** wow. OK, I get it. I will walk through the tests and the code tomorrow and get it in.

Can you post a gist for your performance test harness?

**Comment by deitch** [comment]
Yeah, please do post it. I want to add it to the repo, run it now, and save the results in the commit message.

**Comment by janober** [comment]
You should not really care about the 10x slower. That is totally to expect because temp solution was very very basic and did just do a very simple compare.

Here that is more or less the script I did use:
https://gist.github.com/janober/99e819c43ba5227644e9

**Comment by deitch** [comment]
Thanks. I just took your perftest, changed some of the log output, and added it to the repo.

**Comment by deitch** [comment]
I just made the string match vs RegExp change, and reran your perftest. I am seeing no material change in performance. Basically, on my MacBook Air, running at ~640ms for the entire test set +/- 50ms. I redid it multiple times both before and after the change, and same result.

I don't mind including it - the comparison is a lot cleaner - but I am not seeing a performance gain for the RegExp elimination.

**Comment by deitch** [comment]
Never mind. My mistake. I had left a line uncommented, it was still creating the RegExp if not using it. PEBKAC.

**Comment by janober** [comment]
Ah good. Started to wonder ;-) But I guess the real speed gain depends a lot on factors like nodeJS version used or when running in a browser which one and which version. However pretty sure that regex is always slower. Also checked online also there I found that it says that indexOf should always be faster than using a regex.

**Comment by deitch** [comment]
Ok the options extraction to `_getOptions()` is now done as well. I didn't see any real performance improvements, but I imagine a much larger array would show it. Didn't hurt though.

**Comment by deitch** [comment]
Last but not least is "objects in arrays". Does this make sense? If `"cars.cds.title"` should match `{cars: {cds: {title: "abc"}}}` then should it also match items in an array that way? I get where the *value* is in an array, that it can match, see https://github.com/deitch/searchjs#array-primitive

But to have the *key* dig into an array seems confusing? Or not?

**Comment by janober** [comment]
Hm, strange that it does not make it faster in your tests. It should remove some overhead (even though it is a very small one) for each item so it should show itself. In my case I got a speedup with the settings I did set in the performance-test-script.

Not sure if it is confusing with the Array. For me that is something I would simply have expected to work like that. Because without it searchjs simply stops to working after an Array. You can look for simple values in it but not for values in Objects it contains. Would say having Objects in an Array is something totally common and for that reason should be supported. However if you agree with that but not with the syntax then I am not sure how exactly it should look like.

Btw. would really think about cleaning up the indentation like I did in the commits. If you check out the code on github (https://github.com/deitch/searchjs/blob/master/lib/searchjs.js) you can see what I mean (I guess your IDE is hiding it from you). The code is just all over the place. Especially around the end of the file.  That makes it very hard to read and almost impossible to work with it. Two spaces is more or less what people normally use and what the most style guides say.

**Comment by deitch** [comment]
> Hm, strange that it does not make it faster in your tests. It should remove some overhead (even though it is a very small one) for each item so it should show itself. In my case I got a speedup with the settings I did set in the performance-test-script.

Strange indeed, but that is it. It didn't hurt, and it is a better design, so I put it in.

> Not sure if it is confusing with the Array. For me that is something I would simply have expected to work like that. Because without it searchjs simply stops to working after an Array. You can look for simple values in it but not for values in Objects it contains. Would say having Objects in an Array is something totally common and for that reason should be supported. However if you agree with that but not with the syntax then I am not sure how exactly it should look like.

I can see that. Tell you what. If you can explain the syntax in a way that fits with the README - in other words, explain how it works in a way that people will understand - then we can go for it. I always view that as the real test: can I explain it. Just make a modification to the README.md?

> Btw. would really think about cleaning up the indentation like I did in the commits. If you check out the code on github (https://github.com/deitch/searchjs/blob/master/lib/searchjs.js) you can see what I mean (I guess your IDE is hiding it from you). The code is just all over the place. Especially around the end of the file. That makes it very hard to read and almost impossible to work with it. Two spaces is more or less what people normally use and what the most style guides say.

Gosh, not really worth getting into this religious war, is it? Every group, every project, every engineer, has their own preference in the holy war of spaces vs. tabs. jQuery uses tabs; expressjs and angular use 2 spaces; etc.

I have gone both ways in many projects, based on whatever the group or original code creator I forked from or my IDE did. Truth is, I don't care enough to reformat a file to do it. I just stick with what is.

**Comment by janober** [comment]
Will have a look at the Readme.md

Because of the indentation. I think I maybe phrased it not really well. I could honestly not care less if it is tabs or spaces so for sure no religious war to expect from me (even though I use spaces because the most do), and that is the case because if it is done consistent and if it is set up correctly I do not even know.  All I care about is that stuff is formatted nicely in a way that it is easy to read. And that can be done with spaces and tabs. But that is currently not the case. That is what I ment with the end of the file and that your IDE is probably hiding it. Currently it is almost impossible to read that part without reformatting because tabs and spaces are mixed (that is the case in multiple parts of the script and is sometimes even mixed in the same line). I guess you did not click on the link I supplied because else you would have seen what I mean. You can see it particularly well if you check around the "if (oneMatch)" and the "if (options.negator)" blocks. 
So again, I am really totally ok with tabs as long they are used everywhere and the indentation is correct.
One quite easy way to avoid such problems in the future is to add a file called ".editorconfig" (information here: http://editorconfig.org). The most important IDEs already support it by default (even GitHub does) other ones have plugins. In there many things can be defined (you can also find an example in my pull request because I added one). One parameter is "indent_style". If that gets set to "tabs" the IDE will automatically use tabs instead of spaces. That means that everybody who forks searchjs will uses automatically that settings (without having to know or care what they are). And that means that all pull requests will also have the correct format and tab<->spaces mixes will then not happen again so easily.
I do for sure not want to tell you how to run your repro, I just assumed that it is an issue you did not see yourself yet because of your personal IDE settings (so it is kind of a bug you personally can not see) and thought it would be worth telling you about and probably worth fixing.

**Comment by deitch** [comment]
> Will have a look at the Readme.md

Thanks. I am having a hard time grasping the differences and how to use it cleanly if it can go obj->array->obj->etc. Once it is described in a README style that makes it possible for someone else to understand, I should get it too.

> Because of the indentation. I think I maybe phrased it not really well. ....

No offense taken, I assure you. I just accept whatever a project or something was in, or originally did it, and run with it. I don't want to expend even 5 mins changing it from tabs to spaces or spaces to tabs, as long as it is consistent, of course. If it is inconsistent within a project, well, of course it is worth fixing then!

> editorconfig

Hmm, I didn't think of that here. You are saying to use it so that whoever opens it will always automatically have tabs, and thus not have their IDE, which may prefer 2 spaces or 4 spaces, fill those in and then get a mix? That would make a lot of sense.

Adding .editorconfig now.

**Comment by janober** [comment]
Added now the explanation to the Readme: https://github.com/janober/searchjs/commit/af518203b60515c5651eb00189b891e0e757760c

Great then we are on the same page with everything else. 

The editorconfig does not change existing code. It just makes sure that the editor uses the configuration of the project instead of the default one of the user. So now with the editorconfig in the project my IDE will now automatically use tabs instead of spaces. That means that my code (and so pull requests) will now always have the correct format and merging will not mess anything up.

**Comment by deitch** [comment]
OK, *now* I get it. This makes a lot of sense. I need to change it a bit, but I get it.

Why'd you close the PR? It isn't implemented yet!

**Comment by janober** [comment]
Ah thats good.

Must have simply hit the wrong button by accident...

**Comment by deitch** [comment]
OK, got the README adjusted, also added your name to contributors. Almost there...

**Comment by deitch** [comment]
All in 0.6.1 pushed and npm published.

**Pull request closed without merging**
