### PR TITLE
Added range search to strings.

### LINKED ISSUE #36: Text ranges
From the list:
```
[{name: 'larry'}, {name: 'moe'}, {name: 'curly'}]
```
I'd like to query for names between c and l, so in this case it would exclude moe. I tried the following:

```
{name: {from: 'c', to: 'l')}
```
but it seems this isn't supported out of the box. Is there a way to easily do this using searchjs? And furthermore, I'm eventually going to want to do more complex ranges like `{name: {from: 'cu', to: 'la')}`

### PR DESCRIPTION
**Pull request by mikecole**
Fixes #36

### CODE REVIEW

**Comment by deitch** [comment]
Published.

**Comment by mikecole** [comment]
Thanks for your prompt attention. The clean state of the code made this super easy, especially for a JS noob like me,

**Comment by mikecole** [comment]
@deitch I don't know if I was supposed to build the lib scripts, but they don't reflect the change.

**Comment by deitch** [comment]
Sigh, no, I was supposed to. I keep meaning to put this into CI/CD. Good reason now. I will force repush the existing version and then get it into CI/CD.

**Comment by deitch** [comment]
Oh wait, I forgot, I cannot `npm publish --force` anymore. I will cut a new version.

**Comment by deitch** [comment]
OK, working now, and automated in CI, as it should be. Also publishes only the README, package*json and `lib/`, so all nice and clean. Also had to bump to 0.15.0 to get it work. Try now.

**Comment by mikecole** [comment]
Looks good now. Thanks!

**Comment by deitch** [comment]
Thank you @mikecole

**Pull request merged**
