### PR TITLE
Add possibility to overwrite defaults

### PR DESCRIPTION
**Pull request by janober**
Hi,

added now tests for the "setGlobalDefaults" functionality.

### CODE REVIEW

**Comment by janober** [comment]
Ah great, did understand it wrong. Did not see that you did that already. So close the PR. Thanks again!

**Comment by deitch** [comment]
:-)

Pleasure doing business with you!

Can you share how you use the project and what you use it for?

**Comment by janober** [comment]
;-) Ah can you please also publish version 0.8.0 to npm. The latest version right now is 0.7.2

Sure.  The project is: http://link.fish . It gets used to filter the saved entries by whatever the user wants to filter by.

**Comment by deitch** [comment]
Oh oops. I really need to set up automated publishing for all of these projects. npmjs.com should have hooks.

**Comment by deitch** [comment]
Is it like Evernote or similar for links with intelligence about the links themselves?

**Comment by janober** [comment]
Yes kind of. The idea is to make the information on websites use able. Right now bookmark managers do only extract the title of the page and if lucky some kind of image. So none of the information people are actually interested in when they save a website. So what they for example look for an apartment what they do instead, is that they extract the information manually and saved it in things like text-files, email-drafts, spreadsheets, Evernote, ... But are also then not really able to work with the information (like for example sorting & filtering), display it on a map or refresh the data automatically when it changes.
With link.fish all the above is possible and on top it allows you to combine different kind of data. So for example display your bookmarked apartments from craigslist with your favorite restaurants from yelp and work together in real time. 

Thanks for publishing!

**Comment by deitch** [comment]
So it is providing intelligent metadata, allowing intelligent searching? I get it. I like it.

**Comment by janober** [comment]
Very great to hear! Hope other people will as well once I go live ;-)

If you are ever bored I am happy about anybody who tries the beta-version and gives me honest feedback. Especially the hard and unpleasant one. When interested simply write me at info@link.fish .

**Pull request closed without merging**
