### PR TITLE
Add possibility to search for properties on lower levels 

### PR DESCRIPTION
**Pull request by janober**
This allows to search for a property in a lower level when the level is unknown. Examples can be found in the tests. Allows now also to define the max search depth.

It displays again more changes then there actually are because the IDE cleaned again stuff up.

### CODE REVIEW

**Comment by deitch** [comment]
Hey @janober thanks again.

Will review the changes in next day or two and merge them in. Overall it looks like it does the following:

* Until now: check that field A = value B
* Adds: check that any field here at any depth = value B

Is that right? If so, pretty cool. I like it. The performance probably is weak, since you need to check *every* field at *every* depth, but as long as we warn about it, why not?

> It displays again more changes then there actually are because the IDE cleaned again stuff up.

Does that mean that there are a bunch of non-impacting formatting changes? What are those? Sometimes formatting by IDEs can be bad, and if the new indenting is better, happy to take it.

It does look like there are several other commits that have other changes. The messages are things like "search in objects in array" and "speed up text-search by 20%". Weren't those already covered?

Also it says it has conflicts. It looks like this just needs to be rebased.

**Comment by janober** [comment]
Hi,

yes that is correct. That is more or less what it does.

Yes performance wise will not be very fast but because it only does that when this special option is set it should be fine. Did also add some new code (not committed yet) which allows to set the max depth which speeds it up again a lot.
In my use case do I for example know the depth but not the full path. So I have a mix of being able to search for it simply and still not being to slow.
Also is it possible to define parts of a path. So I can for example define something like: "level1.level2.level5.level8". Once all of that is done will then probably create another PR and close this one.

Yes the other commits you can ignore. That are very old ones. Had some issues with git to get it in sync with the your master-branch again. That is maybe also the reason why there are conflicts, even though there should actually be none.

**Comment by janober** [comment]
Did now commit the other changes. It allows now to set the depth like described above and also to overwrite the defaults if needed. So it is for example possible to activate propertySearch in general without having to define it with every parameter.

Did not create another PR think it should be possible without.

Ah because of the formatting. It is not really better it is simply the one that is defined in the ".editorconfig". There it says that tabs should be used and I guess some part of the code did not follow that rule and used spaces instead. So the IDE did replace the spaces with tabs.

**Comment by deitch** [comment]
Everything with `propertySearch` is now merged in via #14 

I didn't merge in the global defaults yet because it is a separate feature and it needs tests.

**Comment by deitch** [comment]
And now it all is in. Closing this one out.

**Comment by janober** [comment]
Great thanks. Did add tests for the global defaults and created a new PR.

**Pull request closed without merging**
