### PR TITLE
resolves #86 support nested object searches

### LINKED ISSUE #86: Multiple conditions in nested objects in an array
Lets assume the JSON object `{cars: [{brand: 'porsche',hp:450},{brand: 'bmw',hp:250},{brand: 'lada',hp:10}]}`
And now I want to check if there is a BMW with more then 300hp. 
If I run the query `{cars.brand: 'bmw', cars.hp: {gt: 300}` I expect to get `false` as there is no BMW with over 300 hp, but I actually get `true`. I assume it's because it first matches the object `{brand: 'bmw',hp:250}` by the `brand` and then `{brand: 'porsche',hp:450}` by the condition on `hp` field -> hence both conditions are met -> `true`

Is it possible to search by multiple conditions for nested object in current implementation? 

I think it is similar question to https://github.com/deitch/searchjs/issues/54 and even maybe https://github.com/deitch/searchjs/issues/3

### PR DESCRIPTION
**Pull request by risinek**
The issue is explained in the issue #86.

### CODE REVIEW

**Review by deitch — DISMISSED** [review]

**Comment by deitch** [comment]
Thanks! Let's let CI run through, and if green, we can merge it in

**Comment by deitch** [comment]
CI is unhappy about something

**Comment by risinek** [comment]
I'm afraid this is caused by node/npm incompability as per the error
> [Build](https://github.com/deitch/searchjs/actions/runs/5821011001/job/15782667999)
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/setup-node@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

and the mentioned blog post https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

i will try to make it run with node16

**Comment by risinek** [comment]
Is there anything I can help you with to move this further?

**Comment by deitch** [comment]
I just redid the CI to clean it up (and get the publish into its own space). Try rebasing and pushing.

**Comment by deitch** [comment]
Actually cleared all of the Dependabot alerts as well.

**Review by deitch — APPROVED** [review]

**Comment by risinek** [comment]
would it be possible to pack new version and publish to npm please? Or is it too time consuming?

**Comment by deitch** [comment]
V1.1.2 is published

**Pull request merged**
